```{r}
library(BSDA)
library(lattice)
library(datasets)

#No. 1
#Two Sided
zsum.test(mean.x = 3.5, sigma.x = 25, n.x = 100, alternative = "greater", mu = 0, conf.level = 0.95)
#One Sided
zsum.test(mean.x = 3.5, sigma.x = 25, n.x = 100, alternative = "less", mu = 0, conf.level = 0.95)
```

```{r}
#No. 2
#Two Sided
tsum.test(mean.x = 75, s.x = 50, n.x = 30, alternative = "two.sided", mu = 0, var.equal = TRUE, conf.level = 0.95)
#One Sided
tsum.test(mean.x = 75, s.x = 50, n.x = 30, alternative = "less", mu = 0, var.equal=TRUE, conf.level=0.95)
```

```{r}
#No. 3
library(MASS)
library(datasets)
data("cabbages")
data2 <- cabbages$VitC
SampelVit <- sample(cabbages$VitC, 20, replace = TRUE)
#One Sided
t.test(SampelVit, mu = 0, conf.level = 0.05, alternative = "two.sided")
#Two Sided
t.test(SampelVit, mu = 0, conf.level = 0.05, alternative = "less")
```

```{r}
#No. 4
hasilCabai <- c(10, 15, 12)
hasilTomat <- c(20, 22, 35, 10, 11)
#Two Sided
t.test(x = hasilCabai, y = hasilTomat, alternative="two.sided", paired = FALSE, var.equal=TRUE, conf.evel = 0.95)
#One Sided
t.test(x = hasilCabai, y = hasilTomat, alternative = "less", paired = FALSE, var.equal = TRUE, conf.evel = 0.95)
```

```{r}
#No. 5
sebelum <- Aids2$diag
sesudah <- Aids2$death
#Two Sided
t.test(x = sebelum, y = sesudah, alternative = "greater", mu = 0.5, paired = TRUE, var.equal = TRUE, conf.level = 0.95)
#One Sided
t.test(x = sebelum, y = sesudah, alternative = "less", mu = 0.5, paired = TRUE, var.equal = TRUE, conf.level = 0.95)
```

```{r}
#No. 6
#table(sebelum, sesudah)
chisq.test(table(sebelum, sesudah))
```

```{r}
#No. 7
kelas = matrix(c(15, 5, 25, 2), 2 ,2)
colnames(kelas) = c("male", "female")
rownames(kelas) = c("naik", "tinggal")
kelas = as.matrix(kelas)
prop.table(kelas)
#Two Sided
fisher.test(kelas, alternative = "greater")
#One Sided
fisher.test(kelas, alternative = "less")
```