library(extraDistr)
library(Rlab)
library(STAT)

# 1. cdf
# Bernoulli
pbern(1, 0.2)
pbern(0, 0.9)
pbern(100, 0.05)

# Binomial
pbinom(5, 10, 0.5)
pbinom(20, 100, 0.25)
pbinom(15, 50, 0.30)

# Geometric
pgeom(5, 0.25)
pgeom(10, 0.05)
pgeom(20, 0.1)

# Hypergeometric
phyper(5, 10, 15, 20)
phyper(5, 20, 20, 15)
phyper(1, 20, 25, 10)

# Poisson
ppois(10, 26)
ppois(100, 140)
ppois(200, 202)

# 2. pmf
# Bernoulli
dbern(0, 0.23)
dbern(1, 0.1)
dbern(500, 0.75)

# Binomial
dbinom(20, 100, 0.1)
dbinom(50, 60, 0.9)
dbinom(100, 500, 0.2)

# Geometric
dgeom(5, 0.2)
dgeom(30, 0.1)
dgeom(1, 0.75)

# Hypergeometric
dhyper(5, 10, 15, 20)
dhyper(1, 25, 10, 8)
dhyper(0, 20, 20, 10)

# Poisson
dpois(5, 10)
dpois(20, 39)
dpois(25, 15)

# 3. Kasus
#   Bernoulli
#   Pada pelemparan sebuah koin, munculnya gambar dianggap sebagai sukses dan angka dianggap gagal. Peluang munculnya angka adalah 0.5 dan koin tersebut dilempar sebanyak 20 kali. Tentukan mean dan variansnya!
Ber <- rbern(20, 0.5)
Ber
mean(Ber)
var(Ber)

#   Binomial
#   Pada pengerjaan 20 soal, peluang mengerjakan soal dengan benar adalah 0.25. Setiap orang yang mengerjakan soal tersebut ingin mendapatkan maksimal 5 salah. Tentukan mean dan variansnya!
Bin <- rbinom(5, 20, 0.75)
Bin
mean(Bin)
var(Bin)

#   Geometric
#   Pada sebuah permainan menembak, penembak memiliki peluang untuk dapat mengenai target sebanyak 0.6 pada setiap tembakan. Jika dalam satu sesi permainan terdapat maksimal 10 kesempatan dan setelah berhasil mengenai target, penembak bias meninggalkan permainan. Berapa mean dan varians kegagalan tembakannya?
Geo <- rgeom(10, 0.6)
Geo
mean(Geo)
var(Geo)

#   Hypergeometric
#   Di dalam sebuah kantong, terdapat 10 kelereng hijau dan 15 kelereng putih. Dari kantong tersebut akan diambil 5 kelereng secara acak tanpa pengembalian. Percobaan tersebut akan dilakukan sebanyak 20 kali. Tentukan mean dan varians banyaknya kelereng hijau yang terambil!
Hyp <- rhyper(20, 10, 15, 5)
Hyp
mean(Hyp)
var(Hyp)

#   Poisson
#   Dalam kesehariannya, seorang barista bisa membuat kopi sebanyak 20 gelas per jam. Pada kasus tertentu, berapa means dan varians barista tersebut jika dilakukan sebanyak 100 kali percobaan?
Poi <- rpois(100, 20)
Poi
mean(Poi)
var(Poi)

# 4. Histogram
# Bernoulli
hist(rbern(5000, prob=0.01))
hist(rbern(5000, prob=0.25))
hist(rbern(5000, prob=0.5))
hist(rbern(5000, prob=0.75))
hist(rbern(5000, prob=0.99))

# Binomial
hist(rbinom(5000, 2, 0.5))
hist(rbinom(5000, 200, 0.01))
hist(rbinom(5000, 1000, 0.25))
hist(rbinom(5000, 10, 0.8))
hist(rbinom(5000, 50, 0.9))

# Geometric
hist(rgeom(5000, 0.05))
hist(rgeom(5000, 0.2))
hist(rgeom(5000, 0.5))
hist(rgeom(5000, 0.75))
hist(rgeom(5000, 0.9))

# Hypergeometric
hist(rhyper(5000, 100, 100, 15))
hist(rhyper(5000, 30, 70, 10))
hist(rhyper(5000, 20, 50, 68))
hist(rhyper(5000, 50, 20, 10))
hist(rhyper(5000, 500, 500, 250))

# Poisson
hist(rpois(5000, 1))
hist(rpois(5000, 5))
hist(rpois(5000, 20))
hist(rpois(5000, 500))
hist(rpois(5000, 1000))
